services:
  products.api:
    image: products.api
    build:
      context: .
      dockerfile: Services/Products/Products.API/Dockerfile
    ports:
      - "5005:80"
#      - "6005:443"
    environment: 
      - Serilog__SeqServerUrl=http://seq:5341
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      # ;https://+:443
      - ConnectionStrings__DefaultConnection=Server=db,1433;Database=HomeCare.ProductDb;User=sa;Password=Admin123;Encrypt=False;TrustServerCertificate=False;
#      - ASPNETCORE_Kestrel__Certificates__Default__Password=Admin123
#      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    depends_on:
        - db
#    volumes:
#      - ~/.aspnet/https:/https:ro 
  db:
    image: mcr.microsoft.com/mssql/server
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Admin123
    volumes:
      - homecaredata:/var/opt/mssql
  seq:
    image: datalust/seq:latest
    ports:
      - "5341:5341"
      - "5342:80"
    environment:
      - ACCEPT_EULA=Y
    volumes:
      - seqdata:/data
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    volumes:
      - homecaremq:/var/lib/rabbitmq
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
volumes:
    homecaredata:
    seqdata:
    homecaremq:
    redisdata:
