services:
  products.api:
    image: products.api
    build:
      context: .
      dockerfile: Services/Products/Products.API/Dockerfile
    ports:
      - "5005:80"
    environment: 
      - Serilog__SeqServerUrl=http://seq:5341
      - EventBus__HostName=rabbitmq
      - EventBus__Port=5672
      - EventBus__UserName=admin
      - EventBus__Password=admin
      - EventBus__SubscriptionClientName=ProductService
      - EventBus__RetryCount=5
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=db,1433;Database=HomeCare.ProductDb;User=sa;Password=Admin123;Encrypt=False;TrustServerCertificate=False;
      - Cloudinary__CloudName=dboijruhe
      - Cloudinary__ApiKey=431114562135728
      - Cloudinary__ApiSecret=tmDw4SrmffqZp2hA2tiDDZgemTU
    restart: always
    depends_on:
      - db
      - rabbitmq
      - seq
      - redis
      
  iac.api:
    image: iac.api
    build:
      context: .
      dockerfile: Services/IAC/IAC.API/Dockerfile
    ports:
        - "5003:80"
    environment:
        - EventBus__HostName=rabbitmq
        - EventBus__Port=5672
        - EventBus__UserName=admin
        - EventBus__Password=admin
        - EventBus__SubscriptionClientName=IdentityService
        - EventBus__RetryCount=5
        - Serilog__SeqServerUrl=http://seq:5341
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=http://+:80
        - ConnectionStrings__Default=Server=db,1433;Database=HomeCare.IacDb;User=sa;Password=Admin123;Encrypt=False;TrustServerCertificate=False;
    restart: always
    depends_on: 
      - db
      - rabbitmq
      - seq
      - redis
  
  customers.api:
    image: customers.api
    build:
      context: .
      dockerfile: Services/Customers/Customers.API/Dockerfile
    ports:
      - "5002:80"
    environment:
      - EventBus__HostName=rabbitmq
      - EventBus__Port=5672
      - EventBus__UserName=admin
      - EventBus__Password=admin
      - EventBus__SubscriptionClientName=CustomerService
      - EventBus__RetryCount=5
      - Serilog__SeqServerUrl=http://seq:5341
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__CustomerDb=Server=db,1433;Database=HomeCare.CustomerDb;User=sa;Password=Admin123;Encrypt=False;TrustServerCertificate=False;
    restart: always
    depends_on:
      - db
      - rabbitmq
      - seq
      - redis
  
  shopping.api:
    image: shopping.api
    build:
      context: .
      dockerfile: Services/Shopping/Shopping.API/Dockerfile
    ports:
      - "5006:80"
    environment:
      - EventBus__HostName=rabbitmq
      - EventBus__Port=5672
      - EventBus__UserName=admin
      - EventBus__Password=admin
      - EventBus__SubscriptionClientName=ShoppingService
      - EventBus__RetryCount=5
      - Serilog__SeqServerUrl=http://seq:5341
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__OrderDb=Server=db,1433;Database=HomeCare.ShoppingDb;User=sa;Password=Admin123;Encrypt=False;TrustServerCertificate=False;
    restart: always
    depends_on:
      - db
      - rabbitmq
      - seq
      - redis
      
  apigateway:
    image: apigateway
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile
    ports:
      - "5000:80"
    restart: always
    environment:
      - Serilog__SeqServerUrl=http://seq:5341
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - Routes__0__DownstreamHostAndPorts__0__Host=customers.api
      - Routes__0__DownstreamHostAndPorts__0__Port=80
      - SwaggerEndPoints__0__Config__0__Url=http://customers.api/swagger/v1/swagger.json
      - Routes__1__DownstreamHostAndPorts__0__Host=iac.api
      - Routes__1__DownstreamHostAndPorts__0__Port=80
      - SwaggerEndPoints__1__Config__0__Url=http://iac.api/swagger/v1/swagger.json
      - Routes__2__DownstreamHostAndPorts__0__Host=products.api
      - Routes__2__DownstreamHostAndPorts__0__Port=80
      - SwaggerEndPoints__2__Config__0__Url=http://products.api/swagger/v1/swagger.json
      - Routes__3__DownstreamHostAndPorts__0__Host=shopping.api
      - Routes__3__DownstreamHostAndPorts__0__Port=80
      - SwaggerEndPoints__3__Config__0__Url=http://shopping.api/swagger/v1/swagger.json
  
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "14433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Admin123
    restart: always
    volumes:
      - homecaredata:/var/opt/mssql
      
  seq:
    image: datalust/seq:latest
    ports:
      - "5341:5341"
      - "5342:80"
    environment:
      - ACCEPT_EULA=Y
    restart: always
    volumes:
      - seqdata:/data
      
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    restart: always
    volumes:
      - homecaremq:/var/lib/rabbitmq
    
  redis:
    image: redis
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - redisdata:/data
      
volumes:
    homecaredata:
    seqdata:
    homecaremq:
    redisdata:
